### ISSUE TITLE
Adapt when used with JS embedded into HTML

### ISSUE THREAD

**Issue by difosfor** [SublimeLinter/SublimeLinter-jscs#14]
I'm currently getting errors like "Expected indentation of 0 characters", "Missing line feed at file end" and "Illegal trailing whitespace" on JavaScript that is embedded into HTML where I should not be getting these errors.

The indentation is fine, it is just adapted to the HTML. If the appropriate amount of levels of indentation would be removed before being passed to JSCS this would not result in errors.

Checking for a line feed at file end is inappropriate for embedded JavaScript blocks. It could be worked around by appending a line feed to the block before passing it to JSCS.

Similarly the trailing whitespace could be trimmed from the JavaScript block string to work around the "trailing whitespace" error.

PS: Also it seems that JavaScript embedded into HTML files that should be excluded by .jscsrc configuration ("excludeFiles": [ "*_/_.html" ]) is still checked and producing errors.

**Comment by thibaultlavoisey** [comment]
Hello,

Same issue here. I bypass the errors by adding `jscs:disable` but trailing whitespace errors persist.

**Comment by braver** [comment]
A lot has happened since this issue was opened. Probably we fixed this by now. If not, let us know (with full debug logs and settings of course).
