### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by sethen** [SublimeLinter/SublimeLinter-jscs#22]
Getting the following output in Sublime Text 3 build 3083 on Mac OSX in debug mode with Sublime Linter, Sublime Linter jscs and jscs npm bundle installed:

`SublimeLinter: jscs: something.js ['/usr/local/bin/jscs', '-r', 'checkstyle', '--config', '/Users/sethen/Desktop/projects/dotfiles/.jscsrc']`
`SublimeLinter: jscs output: undefined is not a function`

I can validate that jscs is in my path:

`%: $SHELL -l -c '/usr/bin/which jscs'`
`/usr/local/bin/jscs`

Uninstalling and reinstalling everything does nothing.  Any thoughts here?

**Comment by i-akhmadullin** [comment]
Does jscs works when invoked in command line ? What version of node/io.js do you have installed?

**Comment by sethen** [comment]
Ah, this looks like this is an error with jscs actually.

In my frustration, I actually moved over to ESLint as it looked like it provided everything I wanted in one package rather than tracking this error down.

For documentation purposes only, I am using node v0.12.1.  I may open up an issue on the jscs Github page if I want to reinstall jscs and replicate the issue.
