### ISSUE TITLE
Missing from Package Control?

### ISSUE THREAD

**Issue by mAAdhaTTah** [SublimeLinter/SublimeLinter-jscs#25]
I'm not finding SublimeLinter-jscs from Package Control's search in ST3. Anyone else having this issue?

**Comment by montogeek** [comment]
It is there

**Comment by rasmusfl0e** [comment]
I can't find it either. I tried entering "jscs", "linter", "SublimeLinter-jscs"... no matches.
I'm on Windows 7 (sadly).

**Comment by skj3gg** [comment]
[It's still there](https://packagecontrol.io/packages/SublimeLinter-jscs). Make sure that you don't have the package already installed, or that there isn't a package named SublimeLinter-jscs in your `Packages/` or `Installed Packages/` directories.

**Comment by mAAdhaTTah** [comment]
Yeah, my issue was it was already installed but for some reason it was added to my ignored_packages, so it didn't show anywhere but couldn't be found in Package Control. I've actually had this issue a few times, so if anyone else can't find it, check your ignored packages in your user settings.
