### ISSUE TITLE
I set '--fix' in 'args', but it seems not work 

### ISSUE THREAD

**Issue by Yuri4ever** [SublimeLinter/SublimeLinter-jscs#28]
I set '--fix' in sublimeLinter jscs 'args', but when I save the file, it has not been fixed;
In CLI with option '--fix', it works well;
Anybody else has this problem?

**Comment by thomasjonas** [comment]
I also noticed this... Is this feature maybe not implemented?

**Comment by groteworld** [comment]
To my knowledge, jscs doesn't support a stdin passing of the document, so SL makes a duplicate tmp file and sends that to the executable. the `--fix` arg IS being executed, but on a temporary file that gets cleaned up. autocorrectors are not currently supported in SL.

[Here's some documentation on this temp file](http://www.sublimelinter.com/en/latest/linter_attributes.html#tempfile-suffix)

**Comment by thomasjonas** [comment]
Ah, right. I already found that temporary file in the debug logs, but couldn't open it (probably already cleaned up...) I guess this issue can be closed until there's support for autocorrection...
