### ISSUE TITLE
Affecting .coffee files without any .jscsrc

### ISSUE THREAD

**Issue by rahatarmanahmed** [SublimeLinter/SublimeLinter-jscs#33]
My coffeescript projects use tabs, but whenever I save them with the jscs linter enabled, it converts all tabs to spaces. I don't have a .jscsrc in this directory or any parent directory.

**Comment by i-akhmadullin** [comment]
Are you sure that it's not [Editorconfig](https://github.com/sindresorhus/editorconfig-sublime#readme) plugin that changes indentation in files?

**Comment by rahatarmanahmed** [comment]
My bad, you're right. I don't know why disabling SublimeLinter-jscs made it stop changing tabs, but now I can't reproduce it.
