### ISSUE TITLE
Missing semicolon it's not indicated on side.

### ISSUE THREAD

**Issue by pawelgrzybek** [SublimeLinter/SublimeLinter-jscs#35]
Hello. When I run jscs via command line it notifies me about Missing semicolon error. The indicator dot doesn't pop on Sublime Text. Any reasons, or maybe wrong configuration?

**Comment by studiorgb** [comment]
Im so sorry. I found an issue. I jut updated global version of jscs 'sudo npm install -g jscs' and that helped. Sorry guys!
