### ISSUE TITLE
SublimeLinter-jscs is absent from package control.

### ISSUE THREAD

**Issue by krave1986** [SublimeLinter/SublimeLinter-jscs#37]
![sublimelinter](https://cloud.githubusercontent.com/assets/16416541/13278853/a343cca8-db0e-11e5-97c5-169274bf9464.png)
SublimeLinter-jscs is suddenly invisible on package control on sublime text 3.
Any advice?

**Comment by groteworld** [comment]
Make sure you don't have it already installed in your `Sublime Text 3/Installed Packages` or `Sublime Text 3/Packages` directory. You should also check your PackageControl settings file to see if it has `SublimeLinter-jscs` in the `installed_packages` array. Removing any of these cases should allow you to see it in Package Control's command palette. Try restarting ST as well, sometimes it gets weird.

**Comment by krave1986** [comment]
Yes, exactly. I thought sublimelinter-jscs were not installed on the machine when checking via `preferences` - `browse package`. There seemingly is nothing related with jscs in the directory. But in fact it is available while I can find it in `Package control: remove package`.
Thank you very much. My fault.
