### ISSUE TITLE
SublimeLinter-jscs doesn't work with .jscsrc

### ISSUE THREAD

**Issue by whatyouhide** [SublimeLinter/SublimeLinter-jscs#4]
I'm on Mac OSX 10.9.1, Sublime Text 3.
`node` and `jscs` are in my `$PATH`.

I quote the [jscs](https://github.com/mdevils/node-jscs#configuration) readme:

> If there is no --config option specified, jscs will take config from the package.json file > under the jscsConfig if present, if not, it will search for .jscsrc and .jscs.json files in the current working directory or in nearest ancestor until it hits the system root.

The SublimeLinter-jscs readme says that jscs accepts only `.jscs.json` config files in the linted file's directory, which is no longer true.
That doesn't break anything, but when I try to use the new naming for config files (`.jscsrc`) SublimeLinter-jscs doesn't lint anything.

**Comment by whatyouhide** [comment]
@alexilyaev I'm sorry, I gave up using Sublime five or six months ago. Won't be able to test. I'm gonna close for now, if anyone has a problem just comment on the issue and I'll reopen it.

**Comment by sscaff1** [comment]
@jonathanmv Is it possible to provide an absolute path to a jscsrc or eslintrc file?

**Comment by jonathanmv** [comment]
Hey @xw332 and @sscaff1 
It's been long time since I stopped using Sublime and it's hard to remember any other configurations or options to get things working. I'm sorry I cannot help at the moment.

**Comment by sscaff1** [comment]
@jonathanmv I primarily use Atom as well. At work, we use different linting and editor configs than I normally use for personal projects and contract work. I wanted to basically use Atom for my contract work and Sublime for my work at work. I'm not sure how exactly to get the linting settings in place though.

**Comment by alexilyaev** [comment]
**JSCS has been merged into ESLint:**
- http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint
- https://github.com/jscs-dev/node-jscs

You should stop using it.
As for Sublime, it's a dying software, though still good for quick edits in large files.

**Comment by sscaff1** [comment]
@alexilyaev Yes we are trying to make the transition. The problem is my company has been on jscs for some time (I'm actually trying to lead the transition to eslint). One thing stopping us is this:
https://github.com/eslint/eslint/issues/7775
As soon as that rule is supported by ESLINT then our .jscsrc file will translate to 100% to a .eslintrc. I've never used JSCS for personal or contract work, but I have no choice at the place that pays my salary.
